### ISSUE TITLE
get-started.md | 3 links are not working correctly

### ISSUE THREAD

**Issue by schwesig** [aicoe-aiops/pet-image-detection#12]
**Describe the bug**
3 links on [Pet Image Detection - Get Started](https://www.operate-first.cloud/data-science/pet-image-detection/docs/get-started.md) lead to an error (page) and/or not the expected behavior.

**To Reproduce**
1. Go to https://www.operate-first.cloud/data-science/pet-image-detection/docs/get-started.md
2. Click on
2.a. **JupyterHub** in Line 8 "[..] containerized notebook images on the public JupyterHub instance [..]"
2.b. **JupyterHub** in Line 10 "1. Visit the Operate First JupyterHub [..]"
2.c. **here** in Line 18 "[..] video is available here and slides avaiable here. This talk explains [..]"
3. Link goes to
3.a. https://jupyterhub-opf-jupyterhub.apps.zero.massopen.cloud
3.b. https://jupyterhub-opf-jupyterhub.apps.zero.massopen.cloud
3.c. ../slides (https://www.operate-first.cloud/data-science/pet-image-detection/slides)
4. Produces Error
4.a. This site can’t be reachedjupyterhub-opf-jupyterhub.apps.zero.massopen.cloud refused to connect.
4.b. This site can’t be reachedjupyterhub-opf-jupyterhub.apps.zero.massopen.cloud refused to connect.
4.c. 404 Not Found | You just hit a route that doesn't exist... the sadness.

**Expected behaviour**
1. Expected
1.a. Login to JupyterHub on Operate First (smaug?!)
1.b. Login to JupyterHub on Operate First (smaug?!)
1.c. https://github.com/aicoe-aiops/pet-image-detection/tree/main/slides

**Ideas for Solution**
1. Ideas
1.a. change link to smaug
1.b. change link to smaug
1.c. change relative link in source to absolute link (../slides  -->  https://github.com/aicoe-aiops/pet-image-detection/tree/main/slides)

**Screenshots**
n/a

**Additional context**
n/a

**Comment by schwesig** [comment]
**ToDo**
- [ ] Change link 1 [JupyterHub](https://jupyterhub-opf-jupyterhub.apps.zero.massopen.cloud) in line 8
- [ ] Change link 2 [JupyterHub](https://jupyterhub-opf-jupyterhub.apps.zero.massopen.cloud) in line 10
- [ ] Change link 3 [here](../slides ) in line 18
